# config path: '~/.config/alacritty/alacritty.toml'

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#625e4c"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4005f"
red = "#f4005f"
white = "#f6f6ef"
yellow = "#e0d561"

[colors.normal]
black = "#1a1a1a"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4005f"
red = "#f4005f"
white = "#c4c5b5"
yellow = "#fa8419"

[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Quit"
key = "q"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001cc"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C&"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Cp"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001Cn"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u001C1"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C2"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C3"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C4"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C5"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C6"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C7"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C8"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001C9"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Back"

[scrolling]
history = 10000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window.dimensions]
columns = 90
lines = 25

[window.padding]
x = 2
y = 2
